// Code generated by MockGen. DO NOT EDIT.
// Source: metric.go

// Package metric is a generated GoMock package.
package metric

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockStatsService is a mock of StatsService interface.
type MockStatsService struct {
	ctrl     *gomock.Controller
	recorder *MockStatsServiceMockRecorder
}

// MockStatsServiceMockRecorder is the mock recorder for MockStatsService.
type MockStatsServiceMockRecorder struct {
	mock *MockStatsService
}

// NewMockStatsService creates a new mock instance.
func NewMockStatsService(ctrl *gomock.Controller) *MockStatsService {
	mock := &MockStatsService{ctrl: ctrl}
	mock.recorder = &MockStatsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsService) EXPECT() *MockStatsServiceMockRecorder {
	return m.recorder
}

// Distribution mocks base method.
func (m *MockStatsService) Distribution(name string, value int64, tags []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Distribution", name, value, tags)
}

// Distribution indicates an expected call of Distribution.
func (mr *MockStatsServiceMockRecorder) Distribution(name, value, tags interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Distribution", reflect.TypeOf((*MockStatsService)(nil).Distribution), name, value, tags)
}

// Timing mocks base method.
func (m *MockStatsService) Timing(name string, value time.Duration, tags []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Timing", name, value, tags)
}

// Timing indicates an expected call of Timing.
func (mr *MockStatsServiceMockRecorder) Timing(name, value, tags interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Timing", reflect.TypeOf((*MockStatsService)(nil).Timing), name, value, tags)
}

// MockAPIStatsService is a mock of APIStatsService interface.
type MockAPIStatsService struct {
	ctrl     *gomock.Controller
	recorder *MockAPIStatsServiceMockRecorder
}

// MockAPIStatsServiceMockRecorder is the mock recorder for MockAPIStatsService.
type MockAPIStatsServiceMockRecorder struct {
	mock *MockAPIStatsService
}

// NewMockAPIStatsService creates a new mock instance.
func NewMockAPIStatsService(ctrl *gomock.Controller) *MockAPIStatsService {
	mock := &MockAPIStatsService{ctrl: ctrl}
	mock.recorder = &MockAPIStatsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIStatsService) EXPECT() *MockAPIStatsServiceMockRecorder {
	return m.recorder
}

// CaptureLatency mocks base method.
func (m *MockAPIStatsService) CaptureLatency(ctx context.Context, req CaptureLatencyRequest) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CaptureLatency", ctx, req)
}

// CaptureLatency indicates an expected call of CaptureLatency.
func (mr *MockAPIStatsServiceMockRecorder) CaptureLatency(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CaptureLatency", reflect.TypeOf((*MockAPIStatsService)(nil).CaptureLatency), ctx, req)
}
