// Code generated by MockGen. DO NOT EDIT.
// Source: keystore.go

// Package keystore is a generated GoMock package.
package keystore

import (
	reflect "reflect"

	crypto "github.com/circlefin/arc-remote-signer/internal/enclave/common/crypto"
	gomock "github.com/golang/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockProvider) Get(ciphertext []byte) crypto.Key {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ciphertext)
	ret0, _ := ret[0].(crypto.Key)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockProviderMockRecorder) Get(ciphertext interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockProvider)(nil).Get), ciphertext)
}

// Set mocks base method.
func (m *MockProvider) Set(ciphertext []byte, secretKey crypto.Key) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ciphertext, secretKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockProviderMockRecorder) Set(ciphertext, secretKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockProvider)(nil).Set), ciphertext, secretKey)
}
