// This file is derived from:
// https://github.com/ava-labs/avalanchego/blob/master/proto/signer/signer.proto

syntax = "proto3";

package arc.signer.v1;

option go_package = "github.com/circlefin/arc-remote-signer/proto/pb";

service SignerService {
  rpc PublicKey(PublicKeyRequest) returns (PublicKeyResponse) {}
  rpc Sign(SignRequest) returns (SignResponse) {}
}

message PublicKeyRequest {}
message PublicKeyResponse {
  bytes public_key = 1;
  // attestation_document binds public_key to the Nitro enclave. It is empty
  // when Nitro mode is disabled.
  bytes attestation_document = 2;
}

message SignRequest {
  bytes message = 1;
}
message SignResponse {
  bytes signature = 1;
}
