// Code generated by MockGen. DO NOT EDIT.
// Source: enclave.go

// Package enclave is a generated GoMock package.
package enclave

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// AttestationDocument mocks base method.
func (m *MockProvider) AttestationDocument() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttestationDocument")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// AttestationDocument indicates an expected call of AttestationDocument.
func (mr *MockProviderMockRecorder) AttestationDocument() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttestationDocument", reflect.TypeOf((*MockProvider)(nil).AttestationDocument))
}

// DecryptKMSEnvelopedKey mocks base method.
func (m *MockProvider) DecryptKMSEnvelopedKey(ciphertext []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptKMSEnvelopedKey", ciphertext)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptKMSEnvelopedKey indicates an expected call of DecryptKMSEnvelopedKey.
func (mr *MockProviderMockRecorder) DecryptKMSEnvelopedKey(ciphertext interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptKMSEnvelopedKey", reflect.TypeOf((*MockProvider)(nil).DecryptKMSEnvelopedKey), ciphertext)
}
