// Code generated by MockGen. DO NOT EDIT.
// Source: enclave.go

// Package enclave is a generated GoMock package.
package enclave

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	request "github.com/hf/nsm/request"
	response "github.com/hf/nsm/response"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// Attest mocks base method.
func (m *MockProvider) Attest(userData []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attest", userData)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Attest indicates an expected call of Attest.
func (mr *MockProviderMockRecorder) Attest(userData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attest", reflect.TypeOf((*MockProvider)(nil).Attest), userData)
}

// AttestationDocument mocks base method.
func (m *MockProvider) AttestationDocument() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttestationDocument")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// AttestationDocument indicates an expected call of AttestationDocument.
func (mr *MockProviderMockRecorder) AttestationDocument() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttestationDocument", reflect.TypeOf((*MockProvider)(nil).AttestationDocument))
}

// DecryptKMSEnvelopedKey mocks base method.
func (m *MockProvider) DecryptKMSEnvelopedKey(ciphertext []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptKMSEnvelopedKey", ciphertext)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptKMSEnvelopedKey indicates an expected call of DecryptKMSEnvelopedKey.
func (mr *MockProviderMockRecorder) DecryptKMSEnvelopedKey(ciphertext interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptKMSEnvelopedKey", reflect.TypeOf((*MockProvider)(nil).DecryptKMSEnvelopedKey), ciphertext)
}

// MocknsmSession is a mock of nsmSession interface.
type MocknsmSession struct {
	ctrl     *gomock.Controller
	recorder *MocknsmSessionMockRecorder
}

// MocknsmSessionMockRecorder is the mock recorder for MocknsmSession.
type MocknsmSessionMockRecorder struct {
	mock *MocknsmSession
}

// NewMocknsmSession creates a new mock instance.
func NewMocknsmSession(ctrl *gomock.Controller) *MocknsmSession {
	mock := &MocknsmSession{ctrl: ctrl}
	mock.recorder = &MocknsmSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknsmSession) EXPECT() *MocknsmSessionMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MocknsmSession) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MocknsmSessionMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MocknsmSession)(nil).Close))
}

// Send mocks base method.
func (m *MocknsmSession) Send(arg0 request.Request) (response.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(response.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MocknsmSessionMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MocknsmSession)(nil).Send), arg0)
}
