// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/circlefin/arc-remote-signer/proto/pb (interfaces: EnclaveServiceClient)

// Package enclave is a generated GoMock package.
package enclave

import (
	context "context"
	reflect "reflect"

	pb "github.com/circlefin/arc-remote-signer/proto/pb"
	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockEnclaveServiceClient is a mock of EnclaveServiceClient interface.
type MockEnclaveServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockEnclaveServiceClientMockRecorder
}

// MockEnclaveServiceClientMockRecorder is the mock recorder for MockEnclaveServiceClient.
type MockEnclaveServiceClientMockRecorder struct {
	mock *MockEnclaveServiceClient
}

// NewMockEnclaveServiceClient creates a new mock instance.
func NewMockEnclaveServiceClient(ctrl *gomock.Controller) *MockEnclaveServiceClient {
	mock := &MockEnclaveServiceClient{ctrl: ctrl}
	mock.recorder = &MockEnclaveServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnclaveServiceClient) EXPECT() *MockEnclaveServiceClientMockRecorder {
	return m.recorder
}

// GenerateKey mocks base method.
func (m *MockEnclaveServiceClient) GenerateKey(arg0 context.Context, arg1 *pb.GenerateKeyRequest, arg2 ...grpc.CallOption) (*pb.GenerateKeyResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GenerateKey", varargs...)
	ret0, _ := ret[0].(*pb.GenerateKeyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateKey indicates an expected call of GenerateKey.
func (mr *MockEnclaveServiceClientMockRecorder) GenerateKey(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateKey", reflect.TypeOf((*MockEnclaveServiceClient)(nil).GenerateKey), varargs...)
}

// GetPublicKey mocks base method.
func (m *MockEnclaveServiceClient) GetPublicKey(arg0 context.Context, arg1 *pb.GetPublicKeyRequest, arg2 ...grpc.CallOption) (*pb.GetPublicKeyResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPublicKey", varargs...)
	ret0, _ := ret[0].(*pb.GetPublicKeyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicKey indicates an expected call of GetPublicKey.
func (mr *MockEnclaveServiceClientMockRecorder) GetPublicKey(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicKey", reflect.TypeOf((*MockEnclaveServiceClient)(nil).GetPublicKey), varargs...)
}

// Initialize mocks base method.
func (m *MockEnclaveServiceClient) Initialize(arg0 context.Context, arg1 *pb.InitializeRequest, arg2 ...grpc.CallOption) (*pb.InitializeResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Initialize", varargs...)
	ret0, _ := ret[0].(*pb.InitializeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Initialize indicates an expected call of Initialize.
func (mr *MockEnclaveServiceClientMockRecorder) Initialize(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialize", reflect.TypeOf((*MockEnclaveServiceClient)(nil).Initialize), varargs...)
}

// SignMessage mocks base method.
func (m *MockEnclaveServiceClient) SignMessage(arg0 context.Context, arg1 *pb.SignMessageRequest, arg2 ...grpc.CallOption) (*pb.SignMessageResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SignMessage", varargs...)
	ret0, _ := ret[0].(*pb.SignMessageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignMessage indicates an expected call of SignMessage.
func (mr *MockEnclaveServiceClientMockRecorder) SignMessage(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignMessage", reflect.TypeOf((*MockEnclaveServiceClient)(nil).SignMessage), varargs...)
}
