name: Build Docker

on:
  pull_request:
    types: [labeled, synchronize]
    branches:
      - main
      - release/*
  push:
    tags:
      - "v*"

concurrency:
  group: docker-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  enclave:
    if: >-
      github.event_name == 'push' ||
      contains(github.event.pull_request.labels.*.name, 'build-docker')
    uses: ./.github/workflows/nitro-enclave-build.yaml

  docker:
    needs: [enclave]
    uses: ./.github/workflows/build-enclave-image.yaml
    with:
      push: ${{ github.event_name == 'push' }}
      version: ${{ github.ref_name }}
      enclave_artifact_name: ${{ needs.enclave.outputs.image_artifact_name }}
      enclave_file: ${{ needs.enclave.outputs.output_file }}
      enclave_pcr0: ${{ needs.enclave.outputs.pcr0 }}
      enclave_pcr1: ${{ needs.enclave.outputs.pcr1 }}
      enclave_pcr2: ${{ needs.enclave.outputs.pcr2 }}
