name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  ci:
    uses: ./.github/workflows/pipeline-common-ci.yaml

  scan:
    needs: [ci]
    if: ${{ github.event_name == 'pull_request' }}
    uses: circlefin/circle-public-github-workflows/.github/workflows/pr-scan.yaml@v1

  release-sbom:
    needs: [ci]
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    uses: circlefin/circle-public-github-workflows/.github/workflows/attach-release-assets.yaml@v1
